class ExceptionCustom{
  final String message;

  ExceptionCustom([this.message = 'ha sucedido un fallo']);
}